### ISSUE TITLE
Cannot execute the command npm run dev.

### ISSUE THREAD

**Issue by vasvi-sood** [ishanmadan1996/Ethereum-Charity-Donation-DApp#2]
Error message ERROR in ./app/styles/app.css (./node_modules/css-loader!./node_modules/sass-loader/lib/loader.js!./app/styles/app.css)
Module build failed (from ./node_modules/sass-loader/lib/loader.js):
Error: Node Sass does not yet support your current environment: Windows 64-bit with Unsupported runtime (83)
For more information on which environments are supported please see:
https://github.com/sass/node-sass/releases/tag/v4.10.0
    at module.exports (C:\Users\Vasvi Sood\sample2\node_modules\node-sass\lib\binding.js:13:13)
    at Object.<anonymous> (C:\Users\Vasvi Sood\sample2\node_modules\node-sass\lib\index.js:14:35)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.sassLoader (C:\Users\Vasvi Sood\sample2\node_modules\sass-loader\lib\loader.js:46:72)
 @ ./app/styles/app.css 2:14-120
 @ ./app/scripts/index.js
 @ multi (webpack)-dev-server/client?http://localhost:8080 ./app/scripts/index.js

Note: I'm using truffle develop instead of testrpc.

**Comment by vasvi-sood** [comment]
the web page is now opening, used dev: "lite-server" in package.json

**Comment by vasvi-sood** [comment]
But the webpage is not showing.Can you please tell metamask rpc url  and chainId I must use?
